//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MemberAcctStatementImplSoapBinding", Namespace="http://memberAcctStmt.src.tp.com")]
public partial class MemberAcctStatementImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getTPOperationCompleted;
    
    /// <remarks/>
    public MemberAcctStatementImplService() {
        this.Url = "http://45.68.20.134:8080/pensionadmin/services/MemberAcctStatementImpl";
    }
    
    /// <remarks/>
    public event getTPCompletedEventHandler getTPCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://memberAcctStmt.src.tp.com", ResponseNamespace="http://memberAcctStmt.src.tp.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getTPReturn")]
    public ResultType getTP(GetRequestType getRequest) {
        object[] results = this.Invoke("getTP", new object[] {
                    getRequest});
        return ((ResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetTP(GetRequestType getRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getTP", new object[] {
                    getRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResultType EndgetTP(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResultType)(results[0]));
    }
    
    /// <remarks/>
    public void getTPAsync(GetRequestType getRequest) {
        this.getTPAsync(getRequest, null);
    }
    
    /// <remarks/>
    public void getTPAsync(GetRequestType getRequest, object userState) {
        if ((this.getTPOperationCompleted == null)) {
            this.getTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTPOperationCompleted);
        }
        this.InvokeAsync("getTP", new object[] {
                    getRequest}, this.getTPOperationCompleted, userState);
    }
    
    private void OngetTPOperationCompleted(object arg) {
        if ((this.getTPCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getTPCompleted(this, new getTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class GetRequestType {
    
    private DateRangeType dateRangeField;
    
    private string xmlStringField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DateRangeType dateRange {
        get {
            return this.dateRangeField;
        }
        set {
            this.dateRangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string xmlString {
        get {
            return this.xmlStringField;
        }
        set {
            this.xmlStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class DateRangeType {
    
    private string dateFromField;
    
    private string dateToField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string dateFrom {
        get {
            return this.dateFromField;
        }
        set {
            this.dateFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string dateTo {
        get {
            return this.dateToField;
        }
        set {
            this.dateToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class PaymentsOutType {
    
    private string chargesField;
    
    private string claimsField;
    
    private string totalField;
    
    private string wopField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string charges {
        get {
            return this.chargesField;
        }
        set {
            this.chargesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string claims {
        get {
            return this.claimsField;
        }
        set {
            this.claimsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string wop {
        get {
            return this.wopField;
        }
        set {
            this.wopField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class SummaryType {
    
    private string adjustmentsField;
    
    private string adminTVField;
    
    private string closingBalanceField;
    
    private string investmentPerformanceField;
    
    private string openingBalanceField;
    
    private string paymentsInField;
    
    private PaymentsOutType paymentsOutField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string adjustments {
        get {
            return this.adjustmentsField;
        }
        set {
            this.adjustmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string adminTV {
        get {
            return this.adminTVField;
        }
        set {
            this.adminTVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string closingBalance {
        get {
            return this.closingBalanceField;
        }
        set {
            this.closingBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string investmentPerformance {
        get {
            return this.investmentPerformanceField;
        }
        set {
            this.investmentPerformanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string openingBalance {
        get {
            return this.openingBalanceField;
        }
        set {
            this.openingBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string paymentsIn {
        get {
            return this.paymentsInField;
        }
        set {
            this.paymentsInField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public PaymentsOutType paymentsOut {
        get {
            return this.paymentsOutField;
        }
        set {
            this.paymentsOutField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.msg.tp.com")]
public partial class MsgLevelType {
    
    private string _value_Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string _value_ {
        get {
            return this._value_Field;
        }
        set {
            this._value_Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.msg.tp.com")]
public partial class MessageType {
    
    private System.Nullable<short> idField;
    
    private System.Nullable<bool> idSpecified1Field;
    
    private MsgLevelType levelField;
    
    private System.Nullable<bool> levelSpecified1Field;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("idSpecified", IsNullable=true)]
    public System.Nullable<bool> idSpecified1 {
        get {
            return this.idSpecified1Field;
        }
        set {
            this.idSpecified1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public MsgLevelType level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("levelSpecified", IsNullable=true)]
    public System.Nullable<bool> levelSpecified1 {
        get {
            return this.levelSpecified1Field;
        }
        set {
            this.levelSpecified1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.msg.tp.com")]
public partial class MessagesType {
    
    private MessageType[] messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberAcctStmt.src.tp.com", IsNullable=false)]
    public MessageType[] message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class MoneyTypeGroupType {
    
    private FundAllocationType[] fundAllocationsField;
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public FundAllocationType[] fundAllocations {
        get {
            return this.fundAllocationsField;
        }
        set {
            this.fundAllocationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class FundAllocationType {
    
    private string balanceField;
    
    private FundType fundField;
    
    private string investMentStyleField;
    
    private System.Nullable<decimal> noOfUnitsField;
    
    private string percentageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public FundType fund {
        get {
            return this.fundField;
        }
        set {
            this.fundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string investMentStyle {
        get {
            return this.investMentStyleField;
        }
        set {
            this.investMentStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> noOfUnits {
        get {
            return this.noOfUnitsField;
        }
        set {
            this.noOfUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class FundType {
    
    private string amcField;
    
    private string codeField;
    
    private System.Nullable<bool> coreField;
    
    private string factsheetField;
    
    private FundAssetMixType[] fundAssetMixesField;
    
    private string fundClassField;
    
    private string idField;
    
    private System.Nullable<bool> isUnpricedField;
    
    private string nameField;
    
    private string percentOfMnyTypGrpField;
    
    private System.Nullable<decimal> priceField;
    
    private string priceDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string amc {
        get {
            return this.amcField;
        }
        set {
            this.amcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> core {
        get {
            return this.coreField;
        }
        set {
            this.coreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string factsheet {
        get {
            return this.factsheetField;
        }
        set {
            this.factsheetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberAcctStmt.src.tp.com", IsNullable=false)]
    public FundAssetMixType[] fundAssetMixes {
        get {
            return this.fundAssetMixesField;
        }
        set {
            this.fundAssetMixesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string fundClass {
        get {
            return this.fundClassField;
        }
        set {
            this.fundClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> isUnpriced {
        get {
            return this.isUnpricedField;
        }
        set {
            this.isUnpricedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string percentOfMnyTypGrp {
        get {
            return this.percentOfMnyTypGrpField;
        }
        set {
            this.percentOfMnyTypGrpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string priceDate {
        get {
            return this.priceDateField;
        }
        set {
            this.priceDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class FundAssetMixType {
    
    private string factorField;
    
    private System.Nullable<decimal> percentageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string factor {
        get {
            return this.factorField;
        }
        set {
            this.factorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class InvestmentsType {
    
    private MoneyTypeGroupType[] moneyTypeGroupsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public MoneyTypeGroupType[] moneyTypeGroups {
        get {
            return this.moneyTypeGroupsField;
        }
        set {
            this.moneyTypeGroupsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class TransactionType {
    
    private FundAllocationType fundAllocationField;
    
    private string referenceNoField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public FundAllocationType fundAllocation {
        get {
            return this.fundAllocationField;
        }
        set {
            this.fundAllocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string referenceNo {
        get {
            return this.referenceNoField;
        }
        set {
            this.referenceNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class TransactionsType {
    
    private string dateField;
    
    private TransactionType[] transactionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public TransactionType[] transaction {
        get {
            return this.transactionField;
        }
        set {
            this.transactionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class DetailType {
    
    private TransactionsType[] transactionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
    public TransactionsType[] transactions {
        get {
            return this.transactionsField;
        }
        set {
            this.transactionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberAcctStmt.src.tp.com")]
public partial class ResultType {
    
    private DetailType detailField;
    
    private InvestmentsType investmentsField;
    
    private MessagesType messagesField;
    
    private System.Nullable<bool> successField;
    
    private SummaryType summaryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DetailType detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public InvestmentsType investments {
        get {
            return this.investmentsField;
        }
        set {
            this.investmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public MessagesType messages {
        get {
            return this.messagesField;
        }
        set {
            this.messagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SummaryType summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getTPCompletedEventHandler(object sender, getTPCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResultType)(this.results[0]));
        }
    }
}
