//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MemberInformationImplSoapBinding", Namespace="http://memberInformation.src.tp.com")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IncomeType))]
public partial class MemberInformationImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getOperationCompleted;
    
    /// <remarks/>
    public MemberInformationImplService() {
        this.Url = "http://45.68.20.134:8080/SamMediaTest/services/MemberInformationImpl";
    }
    
    /// <remarks/>
    public event getCompletedEventHandler getCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://memberInformation.src.tp.com", ResponseNamespace="http://memberInformation.src.tp.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("getReturn")]
    public MemberSummaryResultType get(GetRequestType getRequest) {
        object[] results = this.Invoke("get", new object[] {
                    getRequest});
        return ((MemberSummaryResultType)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginget(GetRequestType getRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("get", new object[] {
                    getRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public MemberSummaryResultType Endget(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MemberSummaryResultType)(results[0]));
    }
    
    /// <remarks/>
    public void getAsync(GetRequestType getRequest) {
        this.getAsync(getRequest, null);
    }
    
    /// <remarks/>
    public void getAsync(GetRequestType getRequest, object userState) {
        if ((this.getOperationCompleted == null)) {
            this.getOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOperationCompleted);
        }
        this.InvokeAsync("get", new object[] {
                    getRequest}, this.getOperationCompleted, userState);
    }
    
    private void OngetOperationCompleted(object arg) {
        if ((this.getCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getCompleted(this, new getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberInformation.src.tp.com")]
public partial class GetRequestType {
    
    private string xmlStringField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string xmlString {
        get {
            return this.xmlStringField;
        }
        set {
            this.xmlStringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class UncalculatedBirthBandType {
    
    private string bandField;
    
    private string fromMonthField;
    
    private string fromYearField;
    
    private string genderField;
    
    private string isLastField;
    
    private string pensionAgeMonthField;
    
    private string pensionAgeYearField;
    
    private string pensionDateMonthField;
    
    private string pensionDateYearField;
    
    private string previousIsWideField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string band {
        get {
            return this.bandField;
        }
        set {
            this.bandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string fromMonth {
        get {
            return this.fromMonthField;
        }
        set {
            this.fromMonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string fromYear {
        get {
            return this.fromYearField;
        }
        set {
            this.fromYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string isLast {
        get {
            return this.isLastField;
        }
        set {
            this.isLastField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string pensionAgeMonth {
        get {
            return this.pensionAgeMonthField;
        }
        set {
            this.pensionAgeMonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string pensionAgeYear {
        get {
            return this.pensionAgeYearField;
        }
        set {
            this.pensionAgeYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string pensionDateMonth {
        get {
            return this.pensionDateMonthField;
        }
        set {
            this.pensionDateMonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string pensionDateYear {
        get {
            return this.pensionDateYearField;
        }
        set {
            this.pensionDateYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string previousIsWide {
        get {
            return this.previousIsWideField;
        }
        set {
            this.previousIsWideField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class UncalculatedType {
    
    private UncalculatedBirthBandType[] birthBandField;
    
    private string defaultDobFromDayOfMonthField;
    
    private string defaultPensionDateDayOfMonthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public UncalculatedBirthBandType[] birthBand {
        get {
            return this.birthBandField;
        }
        set {
            this.birthBandField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string defaultDobFromDayOfMonth {
        get {
            return this.defaultDobFromDayOfMonthField;
        }
        set {
            this.defaultDobFromDayOfMonthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string defaultPensionDateDayOfMonth {
        get {
            return this.defaultPensionDateDayOfMonthField;
        }
        set {
            this.defaultPensionDateDayOfMonthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class StatePensionType {
    
    private string calulatedStatePensionDateField;
    
    private System.Nullable<int> statePensionValueField;
    
    private UncalculatedType uncalculatedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string calulatedStatePensionDate {
        get {
            return this.calulatedStatePensionDateField;
        }
        set {
            this.calulatedStatePensionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> statePensionValue {
        get {
            return this.statePensionValueField;
        }
        set {
            this.statePensionValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public UncalculatedType uncalculated {
        get {
            return this.uncalculatedField;
        }
        set {
            this.uncalculatedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class DemographicsType {
    
    private string doBField;
    
    private string genderField;
    
    private StatePensionType statePensionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string doB {
        get {
            return this.doBField;
        }
        set {
            this.doBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public StatePensionType statePension {
        get {
            return this.statePensionField;
        }
        set {
            this.statePensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class UserChoiceType {
    
    private System.Nullable<decimal> annuityField;
    
    private System.Nullable<decimal> drawDownField;
    
    private System.Nullable<decimal> lumpsumField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> annuity {
        get {
            return this.annuityField;
        }
        set {
            this.annuityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> drawDown {
        get {
            return this.drawDownField;
        }
        set {
            this.drawDownField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> lumpsum {
        get {
            return this.lumpsumField;
        }
        set {
            this.lumpsumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class TargetType {
    
    private System.Nullable<int> endAgeField;
    
    private System.Nullable<decimal> legacyGoalValueField;
    
    private string schemeNoField;
    
    private TargetIncomeType targetIncomeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> endAge {
        get {
            return this.endAgeField;
        }
        set {
            this.endAgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> legacyGoalValue {
        get {
            return this.legacyGoalValueField;
        }
        set {
            this.legacyGoalValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string schemeNo {
        get {
            return this.schemeNoField;
        }
        set {
            this.schemeNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TargetIncomeType targetIncome {
        get {
            return this.targetIncomeField;
        }
        set {
            this.targetIncomeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class TargetIncomeType : IncomeType {
    
    private System.Nullable<decimal> discretionaryValueField;
    
    private System.Nullable<decimal> essentialValueField;
    
    private IncomeFrequencyType incomefrequencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> discretionaryValue {
        get {
            return this.discretionaryValueField;
        }
        set {
            this.discretionaryValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> essentialValue {
        get {
            return this.essentialValueField;
        }
        set {
            this.essentialValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IncomeFrequencyType incomefrequency {
        get {
            return this.incomefrequencyField;
        }
        set {
            this.incomefrequencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.cons.tp.com")]
public partial class IncomeFrequencyType {
    
    private string incomeFreqEnumValField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string incomeFreqEnumVal {
        get {
            return this.incomeFreqEnumValField;
        }
        set {
            this.incomeFreqEnumValField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TargetIncomeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherIncomeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DecumIncomeType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class IncomeType {
    
    private FrequencyType frequencyField;
    
    private IncomeSourceOptionType[] incomeSourceOptionsField;
    
    private System.Nullable<decimal> increasePercentageField;
    
    private IncreaseType increaseTypeField;
    
    private System.Nullable<decimal> valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public FrequencyType frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public IncomeSourceOptionType[] incomeSourceOptions {
        get {
            return this.incomeSourceOptionsField;
        }
        set {
            this.incomeSourceOptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> increasePercentage {
        get {
            return this.increasePercentageField;
        }
        set {
            this.increasePercentageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IncreaseType increaseType {
        get {
            return this.increaseTypeField;
        }
        set {
            this.increaseTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.cons.tp.com")]
public partial class FrequencyType {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class IncomeSourceOptionType {
    
    private System.Nullable<int> codeField;
    
    private string descriptionField;
    
    private System.Nullable<bool> selectedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> selected {
        get {
            return this.selectedField;
        }
        set {
            this.selectedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.cons.tp.com")]
public partial class IncreaseType {
    
    private string increaseTypeEnumValField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string increaseTypeEnumVal {
        get {
            return this.increaseTypeEnumValField;
        }
        set {
            this.increaseTypeEnumValField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class OtherIncomeType : IncomeType {
    
    private System.Nullable<int> effectiveFromAgeField;
    
    private IncomeFrequencyType incomefrequencyField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> effectiveFromAge {
        get {
            return this.effectiveFromAgeField;
        }
        set {
            this.effectiveFromAgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IncomeFrequencyType incomefrequency {
        get {
            return this.incomefrequencyField;
        }
        set {
            this.incomefrequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class DecumIncomeType : IncomeType {
    
    private IncomeFrequencyType incomefrequencyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public IncomeFrequencyType incomefrequency {
        get {
            return this.incomefrequencyField;
        }
        set {
            this.incomefrequencyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="ProfileType", Namespace="http://src.cons.tp.com")]
public partial class ProfileType1 {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.profile.tp.com")]
public partial class MilestoneType {
    
    private string codeField;
    
    private string dateField;
    
    private System.Nullable<int> displaySequenceField;
    
    private System.Nullable<bool> isScreenField;
    
    private string nameField;
    
    private System.Nullable<int> percentageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> displaySequence {
        get {
            return this.displaySequenceField;
        }
        set {
            this.displaySequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> isScreen {
        get {
            return this.isScreenField;
        }
        set {
            this.isScreenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.profile.tp.com")]
public partial class ProfileStageType {
    
    private string codeField;
    
    private System.Nullable<bool> completeField;
    
    private System.Nullable<int> displaySequenceField;
    
    private MilestoneType[] milestonesField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> complete {
        get {
            return this.completeField;
        }
        set {
            this.completeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> displaySequence {
        get {
            return this.displaySequenceField;
        }
        set {
            this.displaySequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public MilestoneType[] milestones {
        get {
            return this.milestonesField;
        }
        set {
            this.milestonesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.profile.tp.com")]
public partial class ProfileType {
    
    private System.Nullable<bool> isForwardOnlyField;
    
    private ProfileStageType[] stagesField;
    
    private ProfileType1 typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> isForwardOnly {
        get {
            return this.isForwardOnlyField;
        }
        set {
            this.isForwardOnlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public ProfileStageType[] stages {
        get {
            return this.stagesField;
        }
        set {
            this.stagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ProfileType1 type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class ExternalPensionType {
    
    private System.Nullable<bool> includeField;
    
    private string pensionNameField;
    
    private System.Nullable<decimal> projectedValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> include {
        get {
            return this.includeField;
        }
        set {
            this.includeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string pensionName {
        get {
            return this.pensionNameField;
        }
        set {
            this.pensionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> projectedValue {
        get {
            return this.projectedValueField;
        }
        set {
            this.projectedValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class MetaDataType {
    
    private DisInvestmentStrategyType disInvestmentStrategyField;
    
    private FundAllocationType[] investmentStrategyField;
    
    private ExternalPensionType[] otherExternalPensionField;
    
    private OtherIncomeType[] otherIncomesField;
    
    private ProfileType profileField;
    
    private System.Nullable<int> retirementAgeField;
    
    private TargetType targetField;
    
    private UserChoiceType userChoiceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DisInvestmentStrategyType disInvestmentStrategy {
        get {
            return this.disInvestmentStrategyField;
        }
        set {
            this.disInvestmentStrategyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public FundAllocationType[] investmentStrategy {
        get {
            return this.investmentStrategyField;
        }
        set {
            this.investmentStrategyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public ExternalPensionType[] otherExternalPension {
        get {
            return this.otherExternalPensionField;
        }
        set {
            this.otherExternalPensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public OtherIncomeType[] otherIncomes {
        get {
            return this.otherIncomesField;
        }
        set {
            this.otherIncomesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public ProfileType profile {
        get {
            return this.profileField;
        }
        set {
            this.profileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> retirementAge {
        get {
            return this.retirementAgeField;
        }
        set {
            this.retirementAgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public TargetType target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public UserChoiceType userChoice {
        get {
            return this.userChoiceField;
        }
        set {
            this.userChoiceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class DisInvestmentStrategyType {
    
    private FundAllocationType[] distributionField;
    
    private DisInvestmentStrategyType1 typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public FundAllocationType[] distribution {
        get {
            return this.distributionField;
        }
        set {
            this.distributionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DisInvestmentStrategyType1 type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class FundAllocationType {
    
    private string balanceField;
    
    private FundType fundField;
    
    private string investMentStyleField;
    
    private System.Nullable<decimal> noOfUnitsField;
    
    private string percentageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string balance {
        get {
            return this.balanceField;
        }
        set {
            this.balanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public FundType fund {
        get {
            return this.fundField;
        }
        set {
            this.fundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string investMentStyle {
        get {
            return this.investMentStyleField;
        }
        set {
            this.investMentStyleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> noOfUnits {
        get {
            return this.noOfUnitsField;
        }
        set {
            this.noOfUnitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class FundType {
    
    private string amcField;
    
    private string codeField;
    
    private System.Nullable<bool> coreField;
    
    private string factsheetField;
    
    private FundAssetMixType[] fundAssetMixesField;
    
    private string fundClassField;
    
    private string idField;
    
    private System.Nullable<bool> isUnpricedField;
    
    private string nameField;
    
    private string percentOfMnyTypGrpField;
    
    private System.Nullable<decimal> priceField;
    
    private string priceDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string amc {
        get {
            return this.amcField;
        }
        set {
            this.amcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> core {
        get {
            return this.coreField;
        }
        set {
            this.coreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string factsheet {
        get {
            return this.factsheetField;
        }
        set {
            this.factsheetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public FundAssetMixType[] fundAssetMixes {
        get {
            return this.fundAssetMixesField;
        }
        set {
            this.fundAssetMixesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string fundClass {
        get {
            return this.fundClassField;
        }
        set {
            this.fundClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> isUnpriced {
        get {
            return this.isUnpricedField;
        }
        set {
            this.isUnpricedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string percentOfMnyTypGrp {
        get {
            return this.percentOfMnyTypGrpField;
        }
        set {
            this.percentOfMnyTypGrpField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string priceDate {
        get {
            return this.priceDateField;
        }
        set {
            this.priceDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.common.tp.com")]
public partial class FundAssetMixType {
    
    private string factorField;
    
    private System.Nullable<decimal> percentageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string factor {
        get {
            return this.factorField;
        }
        set {
            this.factorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> percentage {
        get {
            return this.percentageField;
        }
        set {
            this.percentageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="DisInvestmentStrategyType", Namespace="http://src.cons.tp.com")]
public partial class DisInvestmentStrategyType1 {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class ContributionType {
    
    private string contribTypeField;
    
    private string frequencyField;
    
    private FundAllocationType[] fundAllocationsField;
    
    private string unitField;
    
    private System.Nullable<decimal> valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string contribType {
        get {
            return this.contribTypeField;
        }
        set {
            this.contribTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public FundAllocationType[] fundAllocations {
        get {
            return this.fundAllocationsField;
        }
        set {
            this.fundAllocationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class SubAccountType {
    
    private string contributionStructureGroupidField;
    
    private ContributionType[] contributionsField;
    
    private DisInvestmentStrategyType disInvestmentStrategyField;
    
    private FundAllocationType[] holdingsField;
    
    private string idField;
    
    private DecumIncomeType incomeField;
    
    private string investmentGroupIdField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string contributionStructureGroupid {
        get {
            return this.contributionStructureGroupidField;
        }
        set {
            this.contributionStructureGroupidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public ContributionType[] contributions {
        get {
            return this.contributionsField;
        }
        set {
            this.contributionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DisInvestmentStrategyType disInvestmentStrategy {
        get {
            return this.disInvestmentStrategyField;
        }
        set {
            this.disInvestmentStrategyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public FundAllocationType[] holdings {
        get {
            return this.holdingsField;
        }
        set {
            this.holdingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DecumIncomeType income {
        get {
            return this.incomeField;
        }
        set {
            this.incomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string investmentGroupId {
        get {
            return this.investmentGroupIdField;
        }
        set {
            this.investmentGroupIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class SalarytType {
    
    private System.Nullable<decimal> deductionField;
    
    private System.Nullable<decimal> valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> deduction {
        get {
            return this.deductionField;
        }
        set {
            this.deductionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class MemberAccountType {
    
    private string accountClassField;
    
    private string accountNoField;
    
    private string accountTypeField;
    
    private System.Nullable<bool> primaryAccountField;
    
    private SalarytType salaryField;
    
    private string schemeNoField;
    
    private string serviceDateField;
    
    private string statusField;
    
    private SubAccountType[] subAccountsField;
    
    private System.Nullable<int> targetRetirementAgeField;
    
    private string typeField;
    
    private string valuationDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string accountClass {
        get {
            return this.accountClassField;
        }
        set {
            this.accountClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string accountNo {
        get {
            return this.accountNoField;
        }
        set {
            this.accountNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string accountType {
        get {
            return this.accountTypeField;
        }
        set {
            this.accountTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> primaryAccount {
        get {
            return this.primaryAccountField;
        }
        set {
            this.primaryAccountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public SalarytType salary {
        get {
            return this.salaryField;
        }
        set {
            this.salaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string schemeNo {
        get {
            return this.schemeNoField;
        }
        set {
            this.schemeNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string serviceDate {
        get {
            return this.serviceDateField;
        }
        set {
            this.serviceDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public SubAccountType[] subAccounts {
        get {
            return this.subAccountsField;
        }
        set {
            this.subAccountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> targetRetirementAge {
        get {
            return this.targetRetirementAgeField;
        }
        set {
            this.targetRetirementAgeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string valuationDate {
        get {
            return this.valuationDateField;
        }
        set {
            this.valuationDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.member.common.tp.com")]
public partial class MemberSummaryType {
    
    private MemberAccountType[] accountsDataField;
    
    private System.Nullable<int> idField;
    
    private MetaDataType metaDataField;
    
    private DemographicsType userDemographicsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public MemberAccountType[] accountsData {
        get {
            return this.accountsDataField;
        }
        set {
            this.accountsDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public MetaDataType metaData {
        get {
            return this.metaDataField;
        }
        set {
            this.metaDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public DemographicsType userDemographics {
        get {
            return this.userDemographicsField;
        }
        set {
            this.userDemographicsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.service.tp.com")]
public partial class MsgLevelType {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.service.tp.com")]
public partial class MessageType {
    
    private System.Nullable<short> idField;
    
    private System.Nullable<bool> idSpecified1Field;
    
    private MsgLevelType levelField;
    
    private System.Nullable<bool> levelSpecified1Field;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<short> id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("idSpecified", IsNullable=true)]
    public System.Nullable<bool> idSpecified1 {
        get {
            return this.idSpecified1Field;
        }
        set {
            this.idSpecified1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public MsgLevelType level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("levelSpecified", IsNullable=true)]
    public System.Nullable<bool> levelSpecified1 {
        get {
            return this.levelSpecified1Field;
        }
        set {
            this.levelSpecified1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://src.service.tp.com")]
public partial class MessagesType {
    
    private MessageType[] messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://memberInformation.src.tp.com", IsNullable=false)]
    public MessageType[] message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://memberInformation.src.tp.com")]
public partial class MemberSummaryResultType {
    
    private MessagesType messagesField;
    
    private System.Nullable<bool> successField;
    
    private System.Nullable<bool> successSpecified1Field;
    
    private MemberSummaryType userDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public MessagesType messages {
        get {
            return this.messagesField;
        }
        set {
            this.messagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("successSpecified", IsNullable=true)]
    public System.Nullable<bool> successSpecified1 {
        get {
            return this.successSpecified1Field;
        }
        set {
            this.successSpecified1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public MemberSummaryType userData {
        get {
            return this.userDataField;
        }
        set {
            this.userDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void getCompletedEventHandler(object sender, getCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public MemberSummaryResultType Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MemberSummaryResultType)(this.results[0]));
        }
    }
}
