--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, SERVICE_TASK_QUEUE_ID, SERVICE_TASK_ID, SCHEDULE_DATE, 
--     PROCESS_DATE, LOCKED, THREAD_NO, 
--     ACTIVE, STATUS_CD
--  FROM UEXT.SERVICE_TASK_QUEUE
--  Where
--  SERVICE_TASK_ID in (173,169)
--  ORDER BY 4 DESC NULLS LAST;
--
Insert into SERVICE_TASK_QUEUE
   (SERVICE_TASK_QUEUE_ID, SERVICE_TASK_ID, SCHEDULE_DATE, LOCKED, ACTIVE, 
    STATUS_CD)
 Values
   (2180389, 169, TO_DATE('08/14/2015 10:00:00', 'MM/DD/YYYY HH24:MI:SS'), '0', '1', 
    'PE');
COMMIT;
